---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: sfc-{{ .Values.prefix }}
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: {{ .Values.prefix }}-server
