---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: sfc-{{ .Values.prefix }}
spec:
  payload: IP
  matches:
    - match:
{{- if .Values.global.comment }}

      sourceSelector:
        app: {{ .Values.prefix }}-proxy
        app: test
{{- end }}
      route:
        - destination:
          destinationSelector:
            app: {{ .Values.prefix }}-server-foo
{{- if .Values.global.comment }}
    - match:
      route:
        - destination:
          destinationSelector:
            app: {{ .Values.prefix }}-proxy
{{- end }}
